site_name: RADTorch
nav:
    - Home: index.md
    - Installation: install.md
    - Pipeline Module: pipeline.md
    - Visutils Module: visutils.md
    - Datautils Module: datautils.md
    - Dicomutils Module: dicomutils.md
    - Modelsutils Module: modelsutils.md
    - Version log: version.md
    - Copyrights: copyright.md
    - License: license.md

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo:
    icon: 'dashboard'
  # logo: ' '
  favicon: 'img/radtorch_icon.ico'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - 'stylesheets/extra.css'
